name: My First Workflow

on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:

  pull_request:
    branches:
      - main

  push:
    branches:
      - main

  schedule:
     # * is a special character in YAML so you have to quote this string
    - cron: '0 * * * *' 

env: 
  NODE_VERSION: '18'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Print a message
        run: echo "Hello, world!"

  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing all the things..."