apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
data:
  DB_NAME: 'first-db'
  DB_USERNAME: 'root'
  DB_HOST: '10.100.94.115'
  DB_PORT: '5432'
---
apiVersion: v1
kind: Secret
metadata:
  name: db-password-secret
type: Opaque
data:
  db-password: cm9vdA==