apiVersion: v1
kind: ConfigMap
metadata:
  name: <NAME OF THE ConfigMap>
data:
  DB_NAME: first-db
  DB_USER: root
  DB_HOST: <ENTER YOUR DB HOST HERE>
  DB_PORT: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: DB_PASSWORD
type: Opaque
data:
  DB_PASSWORD: cm9vdA==