apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
data:
  DB_NAME: 'first-db'
  DB_USER: 'root'
  DB_HOST: '172.31.43.185'
  DB_PORT: '5432'
---
apiVersion: v1
kind: Secret
metadata:
  name: db-password
type: Opaque
data:
  db-password: cm9vdA==