apiVersion: v1
kind: Service
metadata:
  name: coworking
spec:
  type: LoadBalancer
  selector:
    service: coworking
  ports:
  - name: "5253"
    protocol: TCP
    port: 5253
    targetPort: 5253
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking
  labels:
    name: coworking
spec:
  replicas: 1
  selector:
    matchLabels:
      service: coworking
  template:
    metadata:
      labels:
        service: coworking
    spec:
      containers:
      - name: coworking
        image: 803063329130.dkr.ecr.us-east-1.amazonaws.com/my-first-repo:42
        command: ["python", "app.py"]
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5253
          initialDelaySeconds: 5
          timeoutSeconds: 60
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5253
          initialDelaySeconds: 5
          timeoutSeconds: 60
        envFrom:
        - configMapRef:
            name: demo-config
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: demo-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: demo-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: demo-config
              key: DB_NAME
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: demo-config
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password-secret
              key: db-password      
      restartPolicy: 