name: Github Action Workflow Exercise

# Ensure the workflow runs on schedule (Sunday at 0:00) and on push to the main branch
on:
    # Manual trigger using the workflow_dispatch event
    workflow_dispatch:
    
    pull_request:
      branches:
        - main
  
    push:
      branches:
        - main
  
    schedule:
       # * is a special character in YAML so you have to quote this string
      - cron: '0 0 * * 0' 


# Use a matrix strategy to use Node.js versions 16.x and 18.x
jobs:
  build:

    runs-on: ubuntu-latest

    strategy: 
        matrix:
          node-version: [16.x, 18.x]
          #platform: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      # Check out the code from the repository.
      - uses: actions/checkout@v3

      # Set up a Node.js environment using the specified node version.
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install the dependencies.
      - run: |
            cd  module4_cicd/CI-FullstackApp/backend && npm ci

      # Run the tests.
      - run: |
            cd module4_cicd/CI-FullstackApp/backend && npm test

      # Run the linter.
      - run: |
            echo 'Run the linter'
        # cd module4_cicd/CI-FullstackApp/backend && npm init @eslint/config && npm run lint

      # Send a console message at completion.
      - run: |
          echo "Hello ${{github.actor}}. You pushed to ${{github.repository}} at $(date)."
