name: build-test-deploy_environments
on:
  workflow_dispatch:
  
env:
  # Set Node.js Version
  NODE_VERSION: '18.x'

jobs:
  install-build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    # Set up a Node.js environment using the specified node version.
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    # Install the dependencies.
    - run: |
        cd  module4_cicd/CI-FullstackApp/backend && npm ci
        npm run build --if-present
        npm test 

  stage:
    runs-on: ubuntu-latest
    needs: install-build-test
    environment:
      name: staging

    steps:
      # Simulate a Deployment
      - name: Deploy to Staging
        run: |
         echo "Deployed to staging environment"

  production:
    runs-on: ubuntu-latest
    needs: stage
    environment:
      name: production

    steps:
      # Simulate a Deployment
      - name: Deploy to Production
        run: |
         echo "Deployed to production environment"