name: create cloud formation stack
on:
  workflow_dispatch:
  
env:
  # Set Node.js Version
  NODE_VERSION: '18.x'

jobs:
  install-build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    # Set up a Node.js environment using the specified node version.
    - name: Use Node.js ${{ env.NODE_VERSION}}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    # Install the dependencies.
    - run: |
        cd  module4_cicd/environment && npm ci
        npm run build --if-present
        npm test 

  stage_deploy:
    runs-on: ubuntu-latest
    needs: install-build-test
    environment:
      name: staging

    steps:
      # Simulate a Deployment
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          aws-region: us-east-1

      - name: Create CloudFormation Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with: 
            name: udatest
            template: module4_cicd/environment/udatest.yml
            no-fail-on-empty-changeset: "1"

      - name: Deploy to Staging
        run: |
         echo "Deployed to staging environment"

